StreamOneInterface/ViewModels/ReceivedOrdersViewModel.cs
using StreamOneInterface.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StreamOneInterface.ViewModels
{
    public class ReceivedOrdersViewModel
    {
        public IEnumerable<Order> Orders { get; set; }
        public IEnumerable<OrderRow> OrderRows { get; set; }
        
    }
}

StreamOneInterface/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StreamOneInterface.Models;
using StreamOneInterface.Models.Entities;

namespace StreamOneInterface.Controllers
{
    [Authorize]
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StreamOneNumber,ShareNumber,Name,Description,Active")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StreamOneNumber,ShareNumber,Name,Description,Active")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StreamOneInterface/Controllers/ReceivedOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StreamOneInterface.Models;
using StreamOneInterface.Models.Entities;
using StreamOneInterface.ViewModels;
using PagedList;

namespace StreamOneInterface.Controllers
{
    [Authorize]
    public class ReceivedOrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ReceivedOrders
        public ActionResult Index(int? id, int? orderrowID, int? OrderPage, string currentFilter, string sortOrder, string searchString, int? page)
        {
            /*
             * ViewBag property provides the view with the current sort order, 
             * because this must be included in the paging links 
             * in order to keep the sort order the same while paging:
             * */
            ViewBag.CurrentSort = sortOrder;

            int pageSize = 4;
            int pageNumber = (page ?? 1);

            //int orderPageNumber = (OrderPage ?? 1);

            ViewBag.StatusSortParm = String.IsNullOrEmpty(sortOrder) ? "status_desc" : "";
            ViewBag.StatusDescParm = String.IsNullOrEmpty(sortOrder) ? "status" : "";
            ViewBag.CompanySortParm = sortOrder == "company" ? "company" : "company";
            ViewBag.CompanyDescSortParm = sortOrder == "company" ? "company_desc" : "company";
            ViewBag.StreamOneSortParm = String.IsNullOrEmpty(sortOrder) ? "streamone" : "";
            ViewBag.StreamOneDescSortParm = String.IsNullOrEmpty(sortOrder) ? "streamone_desc" : "";
            ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "date" : "";
            ViewBag.DateDescSortParm = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var viewModel = new ReceivedOrdersViewModel();

                viewModel.Orders = db.Orders
                    .Include(o => o.ApplicationUser)
                    .Include(i => i.OrderStatus)
                    .Include(i => i.Reseller)
                    .Include(i => i.OrderType)
                    .Include(i => i.OrderRows.Select(c => c.Product))
                    .OrderBy(i => i.Id);
           
           

            

            if (!String.IsNullOrEmpty(searchString))
            {
                viewModel.Orders = viewModel.Orders.Where(o => o.OrderStreamOneID.Contains(searchString)
                                                        || o.OrderStatus.Status.Contains(searchString)
                                                        || o.Reseller.Company.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "status":
                    viewModel.Orders = viewModel.Orders.OrderBy(r => r.OrderStatus.Status).ToPagedList(pageNumber, pageSize);
                    break;
                case "status_desc":
                    viewModel.Orders = viewModel.Orders.OrderByDescending(r => r.OrderStatus.Status).ToPagedList(pageNumber, pageSize);
                    break;
                case "streamone":
                    viewModel.Orders = viewModel.Orders.OrderBy(r => r.OrderStreamOneID).ToPagedList(pageNumber, pageSize);
                    break;
                case "streamone_desc":
                    viewModel.Orders = viewModel.Orders.OrderByDescending(r => r.OrderStreamOneID).ToPagedList(pageNumber, pageSize);
                    break;
                case "company":
                    viewModel.Orders = viewModel.Orders.OrderBy(r => r.Reseller.Company).ToPagedList(pageNumber, pageSize);
                    break;
                case "company_desc":
                    viewModel.Orders = viewModel.Orders.OrderByDescending(r => r.Reseller.Company).ToPagedList(pageNumber, pageSize);
                    break;
                case "date":
                    viewModel.Orders = viewModel.Orders.OrderBy(r => r.Date).ToPagedList(pageNumber, pageSize);
                    break;
                case "date_desc":
                    viewModel.Orders = viewModel.Orders.OrderByDescending(r => r.Date).ToPagedList(pageNumber, pageSize);
                    break;
                default:
                    viewModel.Orders = viewModel.Orders.OrderByDescending(s => s.Id).ToPagedList(pageNumber, pageSize);
                    break;
            }

            if (id != null)
            {
                ViewBag.Id = id.Value;

                viewModel.Orders.Count();
                if(viewModel.Orders.Where(i => i.Id == id.Value).SingleOrDefault() != null)
                {
                    viewModel.OrderRows = viewModel.Orders.Where(
                    i => i.Id == id.Value).SingleOrDefault().OrderRows;
                }  
            }

           
            viewModel.Orders.ToPagedList(pageNumber, pageSize);

            //Use the following two formulas so that it doesn't round down on the returned integer
            decimal totalPages = ((decimal)(viewModel.Orders.Count() / (decimal)pageSize));
            ViewBag.TotalPages = Math.Ceiling(totalPages);

            ViewBag.OnePageofOrders = viewModel.Orders;
            ViewBag.PageNumber = pageNumber;
            
            return View(viewModel);
        }

        // GET: ReceivedOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // GET: ReceivedOrders/Create
        public ActionResult Create()
        {
          // ViewBag.UserID = new SelectList(db.ApplicationUsers, "Id", "Email");
            ViewBag.OrderStatusID = new SelectList(db.OrderStatus, "Id", "Status");
            ViewBag.OrderTypeID = new SelectList(db.OrderTypes, "Id", "Type");
            ViewBag.ResellerID = new SelectList(db.Resellers, "Id", "CustomerID");
            return View();
        }

        // POST: ReceivedOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserID,OrderStreamOneID,ListingID,ResellerID,OrderTypeID,LastUpdated,OrderStatusID,Date")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

           // ViewBag.UserID = new SelectList(db.ApplicationUsers, "Id", "Email", order.UserID);
            ViewBag.OrderStatusID = new SelectList(db.OrderStatus, "Id", "Status", order.OrderStatusID);
            ViewBag.OrderTypeID = new SelectList(db.OrderTypes, "Id", "Type", order.OrderTypeID);
            ViewBag.ResellerID = new SelectList(db.Resellers, "Id", "CustomerID", order.ResellerID);
            return View(order);
        }

        // GET: ReceivedOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
           // ViewBag.UserID = new SelectList(db.ApplicationUsers, "Id", "Email", order.UserID);
            ViewBag.OrderStatusID = new SelectList(db.OrderStatus, "Id", "Status", order.OrderStatusID);
            ViewBag.OrderTypeID = new SelectList(db.OrderTypes, "Id", "Type", order.OrderTypeID);
            ViewBag.ResellerID = new SelectList(db.Resellers, "Id", "CustomerID", order.ResellerID);
            return View(order);
        }

        // POST: ReceivedOrders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserID,OrderStreamOneID,ListingID,ResellerID,OrderTypeID,OrderStatusID,Date,LastUpdated")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           // ViewBag.UserID = new SelectList(db.ApplicationUsers, "Id", "Email", order.UserID);
            ViewBag.OrderStatusID = new SelectList(db.OrderStatus, "Id", "Status", order.OrderStatusID);
            ViewBag.OrderTypeID = new SelectList(db.OrderTypes, "Id", "Type", order.OrderTypeID);
            ViewBag.ResellerID = new SelectList(db.Resellers, "Id", "CustomerID", order.ResellerID);
            return View(order);
        }

        // GET: ReceivedOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: ReceivedOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

StreamOneInterface/Views/ReceivedOrders/Create.cshtml
@model StreamOneInterface.Models.Entities.Order

@{
    ViewBag.Title = "Create";
}

<div class="well col-sm-10">
    <h2>Create</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Order</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*<div class="form-group">
                @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.OrderStreamOneID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OrderStreamOneID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OrderStreamOneID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ListingID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ListingID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ListingID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ResellerID, "ResellerID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ResellerID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ResellerID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OrderTypeID, "OrderTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OrderTypeID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OrderTypeID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OrderStatusID, "OrderStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OrderStatusID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OrderStatusID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastUpdated, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastUpdated, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

StreamOneInterface/Views/ReceivedOrders/Details.cshtml
@model StreamOneInterface.Models.Entities.Order

@{
    ViewBag.Title = "Details";
}

<div class="well col-sm-10">
    <h2>Details</h2>

    <div>
        <h4>Order</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ApplicationUser.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ApplicationUser.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OrderStatus.Status)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrderStatus.Status)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OrderType.Type)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrderType.Type)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Reseller.CustomerID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Reseller.CustomerID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OrderStreamOneID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OrderStreamOneID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ListingID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ListingID)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Date)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LastUpdated)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastUpdated)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" })
        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
    </p>
</div>

StreamOneInterface/Views/ReceivedOrders/Edit.cshtml
@model StreamOneInterface.Models.Entities.Order

@{
    ViewBag.Title = "Edit";
}

<div class="well col-sm-10">
    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Order</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            @*<div class="form-group">
                @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.OrderStreamOneID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OrderStreamOneID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OrderStreamOneID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ListingID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ListingID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ListingID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ResellerID, "ResellerID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ResellerID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ResellerID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OrderTypeID, "OrderTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OrderTypeID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OrderTypeID, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.TimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TimeStamp, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TimeStamp, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.OrderStatusID, "OrderStatusID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OrderStatusID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OrderStatusID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastUpdated, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastUpdated, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

StreamOneInterface/Views/ReceivedOrders/Index.cshtml
@model StreamOneInterface.ViewModels.ReceivedOrdersViewModel
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Orders";
}
<div class="well col-sm-10">
    <h3>List of received orders</h3>

    <p>
        @Html.ActionLink("Add new order", "Create", null, new { @class = "btn btn-default" })
    </p>
    <fieldset class="form-group">
        @using (Html.BeginForm("Index", "ReceivedOrders", FormMethod.Get))
        {
            <label>Find by StreamOne ID, Reseller's Company or Order status:</label>
                @Html.TextBox("SearchString", null, new { @class = "form-control" })
                <input type="submit" class="form-control" value="Search" />
        }
    </fieldset>

    <table class="table table-striped table-hover table-condensed">
        <thead class="tableheader">
            <tr>
                <th>
                    @Html.ActionLink("Status", "Index", new { sortOrder = ViewBag.StatusSortParm , currentFilter = ViewBag.CurrentFilter })
                    
                </th>
                <th>
                    @Html.ActionLink("StreamOne ID", "Index", new { sortOrder = ViewBag.StreamOneSortParm, currentFilter = ViewBag.CurrentFilter })
                  
                </th>
                <th>
                    @Html.ActionLink("Reseller", "Index", new { sortOrder = ViewBag.CompanySortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th>
                    @Html.ActionLink("Date", "Index", new { sortOrder = ViewBag.DateSortParm , currentFilter = ViewBag.CurrentFilter })
                </th>
                <th></th>
            </tr>
            </thead>
        <tbody>
            @foreach (var item in Model.Orders)
            {

                string selectedRow = "";
                if (item.Id == ViewBag.Id)
                {
                    selectedRow = "success";
                }
                <tr class="@selectedRow">
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderStatus.Status)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderStreamOneID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Reseller.Company)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-default btn-sm" })
                        @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-default btn-sm" })
                        @* It is not allowed to delete a order
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })*@
                        @Html.ActionLink("Select", "Index", new { id = item.Id }, new { @class = "btn btn-success btn-sm" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
        @Html.PagedListPager((IPagedList)ViewBag.OnePageofOrders, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter}))
    
</div>
<div class="well col-sm-9" id="orderRows">
    @* Order Rows starts here  *@

    @if (Model.OrderRows != null)
    {
        <h4>Order rows of selected order</h4>
        <table class="table table-striped table-hover table-condensed">
            <thead class="tableheader">
                <tr>
                    <th>Item ID</th>
                    <th>Status</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th></th>
                </tr>
           </thead>
            <tbody>
                @foreach (var item in Model.OrderRows)
                {
                    <tr>
                        <td>
                            @item.ItemID
                        </td>
                        <td>
                            @item.OrderRowStatus.RowStatus
                        </td>
                        <td>
                            @item.Product.Name
                        </td>
                        <td>
                            @item.Quantity
                        </td>
                        <td>
                            @item.UnitPrice
                        </td>
                        <td>
                            @Html.ActionLink("Product details", "Details", "Products", new { id = item.ProductID }, new { @class = "btn btn-default btn-sm" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>